export const GET_ALL_SALONS_SUCCESS = "GET_ALL_SALONS_SUCCESS";
export const GET_ALL_SALONS_ERROR = "GET_ALL_SALONS_ERROR";

export const ADD_SALON_SUCCESS = "ADD_SALON_SUCCESS";
export const ADD_SALON_FAIL = "ADD_SALON_FAIL";

export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAIL = "GET_LOCATIONS_FAIL";

export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAIL = "ADD_LOCATIONS_FAIL";

export const PORT = "https://ecrew-back.herokuapp.com/api";
